version: '3.4'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    command: '--auth'
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: welcome
      MONGO_INITDB_DATABASE: test-db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - database

networks:
  database:
    driver: bridge
