version: '3.4'

services:
  post-micro:
    build: .
    container_name: post-micro
    environment:
      - AMWP_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672
      - AMWP_QUEUE=post_queue
    restart: always
    networks:
      - rabbitmq_queue
      - mongodb_database

networks:
  rabbitmq_queue:
    external: true
  mongodb_database:
    external: true
